// ============================================================================
// gfx_roms.v - AUTO-GENERATED by gen_gfx.py.  DO NOT EDIT BY HAND.
//
//  * gfx_palette : 5-bit index -> BT.601 limited-range YCbCr.  The FPGA sends
//                  YCbCr to the ADV7511, whose internal CSC converts back to RGB.
//  * gfx_bird    : 16x12 bird sprite, 3 wing frames, 3 bits/pixel.
//  * gfx_font    : 5x7 glyph ROM for the score and UI text.
//  * gfx_hill    : 64 x 5-bit hill silhouette for the scrolling parallax band.
// ============================================================================
`timescale 1ns / 1ps

// ----------------------------------------------------------------------------
// Palette: index -> {Y, Cb, Cr}
// ----------------------------------------------------------------------------
module gfx_palette (
    input  wire [4:0] idx,
    output reg  [7:0] y,
    output reg  [7:0] cb,
    output reg  [7:0] cr
);
    always @* begin
        case (idx)
            5'd0 : begin y = 8'd127; cb = 8'd189; cr = 8'd95 ; end // SKY0      #4C84FC
            5'd1 : begin y = 8'd151; cb = 8'd175; cr = 8'd97 ; end // SKY1      #6CA4FC
            5'd2 : begin y = 8'd177; cb = 8'd160; cr = 8'd103; end // SKY2      #94C4FC
            5'd3 : begin y = 8'd232; cb = 8'd128; cr = 8'd128; end // CLOUD     #FCFCFC
            5'd4 : begin y = 8'd137; cb = 8'd92 ; cr = 8'd92 ; end // HILL_LT   #54B844
            5'd5 : begin y = 8'd98 ; cb = 8'd102; cr = 8'd96 ; end // HILL_DK   #2C842C
            5'd6 : begin y = 8'd158; cb = 8'd84 ; cr = 8'd97 ; end // BUSH_LT   #74D04C
            5'd7 : begin y = 8'd112; cb = 8'd97 ; cr = 8'd93 ; end // BUSH_DK   #389830
            5'd8 : begin y = 8'd153; cb = 8'd78 ; cr = 8'd93 ; end // GRASS     #68D03C
            5'd9 : begin y = 8'd114; cb = 8'd93 ; cr = 8'd94 ; end // GRASS_DK  #3C9C2C
            5'd10: begin y = 8'd182; cb = 8'd86 ; cr = 8'd150; end // SAND      #E4C06C
            5'd11: begin y = 8'd146; cb = 8'd87 ; cr = 8'd151; end // SAND_DK   #BC9444
            5'd12: begin y = 8'd145; cb = 8'd81 ; cr = 8'd89 ; end // PIPE      #58C838
            5'd13: begin y = 8'd186; cb = 8'd85 ; cr = 8'd102; end // PIPE_HI   #9CEC70
            5'd14: begin y = 8'd69 ; cb = 8'd111; cr = 8'd104; end // PIPE_DK   #18581C
            5'd15: begin y = 8'd193; cb = 8'd44 ; cr = 8'd157; end // BIRD_Y    #FCD824
            5'd16: begin y = 8'd143; cb = 8'd70 ; cr = 8'd181; end // BIRD_O    #E88020
            5'd17: begin y = 8'd232; cb = 8'd128; cr = 8'd128; end // WHITE     #FCFCFC
            5'd18: begin y = 8'd16 ; cb = 8'd128; cr = 8'd128; end // BLACK     #000000
            5'd19: begin y = 8'd232; cb = 8'd128; cr = 8'd128; end // TXT       #FCFCFC
            5'd20: begin y = 8'd43 ; cb = 8'd128; cr = 8'd128; end // TXT_SH    #202020
            5'd21: begin y = 8'd110; cb = 8'd95 ; cr = 8'd200; end // GO_RED    #E0402C
            5'd22: begin y = 8'd105; cb = 8'd84 ; cr = 8'd173; end // BEAK_DK   #B05410
            5'd23: begin y = 8'd102; cb = 8'd98 ; cr = 8'd153; end // GROUND_E  #8C5C28
            5'd24: begin y = 8'd116; cb = 8'd166; cr = 8'd95 ; end // SPARE0    #4080C0
            5'd25: begin y = 8'd117; cb = 8'd161; cr = 8'd99 ; end // SPARE1    #4880B8
            5'd26: begin y = 8'd118; cb = 8'd156; cr = 8'd103; end // SPARE2    #5080B0
            5'd27: begin y = 8'd120; cb = 8'd151; cr = 8'd108; end // SPARE3    #5880A8
            5'd28: begin y = 8'd121; cb = 8'd147; cr = 8'd112; end // SPARE4    #6080A0
            5'd29: begin y = 8'd122; cb = 8'd142; cr = 8'd116; end // SPARE5    #688098
            5'd30: begin y = 8'd123; cb = 8'd137; cr = 8'd120; end // SPARE6    #708090
            5'd31: begin y = 8'd125; cb = 8'd133; cr = 8'd124; end // SPARE7    #788088
            default: begin y = 8'd16; cb = 8'd128; cr = 8'd128; end
        endcase
    end
endmodule

// ----------------------------------------------------------------------------
// Bird sprite: 3 frames x 12 rows x 16 pixels, 3 bits per pixel
//   0=transparent 1=black outline 2=yellow body 3=orange wing
//   4=white eye   5=dark-orange beak tip
// ----------------------------------------------------------------------------
module gfx_bird (
    input  wire [1:0]  frame,
    input  wire [3:0]  px,
    input  wire [3:0]  py,
    output reg  [2:0]  pix
);
    reg [47:0] rowbits;
    always @* begin
        case (frame)
            2'd0: case (py) // frame 0
                4'd0 : rowbits = 48'h000000000000; // ................
                4'd1 : rowbits = 48'h001249000000; // ...KKKKK........
                4'd2 : rowbits = 48'h009649240000; // ..KKOkkKKK......
                4'd3 : rowbits = 48'h04b6e4848000; // .KKOOOWWWKK.....
                4'd4 : rowbits = 48'h25b6e1889200; // KKOOOOWKWYKKK...
                4'd5 : rowbits = 48'h24926489b248; // KkkkkkWWWYOOKKK.
                4'd6 : rowbits = 48'h29249249b748; // KYYYYYYYYYOOOBK.
                4'd7 : rowbits = 48'h25249249b748; // KKYYYYYYYYOOOBK.
                4'd8 : rowbits = 48'h0524924db248; // .KYYYYYYYOOOKKK.
                4'd9 : rowbits = 48'h04a4922c9200; // .KKYYYYYKOKKK...
                4'd10: rowbits = 48'h009249248000; // ..KKKKKKKKK.....
                4'd11: rowbits = 48'h000000000000; // ................
                default: rowbits = 48'h0;
            endcase
            2'd1: case (py) // frame 1
                4'd0 : rowbits = 48'h000000000000; // ................
                4'd1 : rowbits = 48'h001249000000; // ...KKKKK........
                4'd2 : rowbits = 48'h009491240000; // ..KKYYYKKK......
                4'd3 : rowbits = 48'h04a4a4848000; // .KKYYYWWWKK.....
                4'd4 : rowbits = 48'h249261889200; // KKkkkkWKWYKKK...
                4'd5 : rowbits = 48'h25b6e489b248; // KkOOOOWWWYOOKKK.
                4'd6 : rowbits = 48'h2db6d949b748; // KOOOOOOkYYOOOBK.
                4'd7 : rowbits = 48'h24924949b748; // KKkkkkkkYYOOOBK.
                4'd8 : rowbits = 48'h0524924db248; // .KYYYYYYYOOOKKK.
                4'd9 : rowbits = 48'h04a4922c9200; // .KKYYYYYKOKKK...
                4'd10: rowbits = 48'h009249248000; // ..KKKKKKKKK.....
                4'd11: rowbits = 48'h000000000000; // ................
                default: rowbits = 48'h0;
            endcase
            2'd2: case (py) // frame 2
                4'd0 : rowbits = 48'h000000000000; // ................
                4'd1 : rowbits = 48'h001249000000; // ...KKKKK........
                4'd2 : rowbits = 48'h009491240000; // ..KKYYYKKK......
                4'd3 : rowbits = 48'h04a4a4848000; // .KKYYYWWWKK.....
                4'd4 : rowbits = 48'h2524a1889200; // KKYYYYWKWYKKK...
                4'd5 : rowbits = 48'h2924a489b248; // KYYYYYWWWYOOKKK.
                4'd6 : rowbits = 48'h29249249b748; // KYYYYYYYYYOOOBK.
                4'd7 : rowbits = 48'h24924949b748; // KKkkkkkkYYOOOBK.
                4'd8 : rowbits = 48'h05b6d94db248; // .KOOOOOkYOOOKKK.
                4'd9 : rowbits = 48'h04b6c92c9200; // .KKOOOkkKOKKK...
                4'd10: rowbits = 48'h009249248000; // ..KKKKKKKKK.....
                4'd11: rowbits = 48'h000000000000; // ................
                default: rowbits = 48'h0;
            endcase
        endcase
        // 3 bits per pixel, pixel 0 is the most significant group
        pix = rowbits[45 - px*3 +: 3];
    end
endmodule

// ----------------------------------------------------------------------------
// 5x7 glyph ROM: 5 columns x 7 rows, MSB of each row word = leftmost pixel
// ----------------------------------------------------------------------------
module gfx_font (
    input  wire [5:0] glyph,
    input  wire [2:0] px,
    input  wire [2:0] py,
    output reg        pix
);
    reg [4:0] rowbits;
    always @* begin
        case (glyph)
            6'd0 : case (py) // 'space'
                3'd0: rowbits = 5'b00000;
                3'd1: rowbits = 5'b00000;
                3'd2: rowbits = 5'b00000;
                3'd3: rowbits = 5'b00000;
                3'd4: rowbits = 5'b00000;
                3'd5: rowbits = 5'b00000;
                3'd6: rowbits = 5'b00000;
                default: rowbits = 5'b0;
            endcase
            6'd1 : case (py) // 'A'
                3'd0: rowbits = 5'b01100;
                3'd1: rowbits = 5'b10010;
                3'd2: rowbits = 5'b10010;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10010;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b10010;
                default: rowbits = 5'b0;
            endcase
            6'd2 : case (py) // 'B'
                3'd0: rowbits = 5'b11100;
                3'd1: rowbits = 5'b10010;
                3'd2: rowbits = 5'b10010;
                3'd3: rowbits = 5'b11100;
                3'd4: rowbits = 5'b10010;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b11100;
                default: rowbits = 5'b0;
            endcase
            6'd3 : case (py) // 'C'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b10000;
                3'd4: rowbits = 5'b10000;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd4 : case (py) // 'D'
                3'd0: rowbits = 5'b11100;
                3'd1: rowbits = 5'b10010;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b11100;
                default: rowbits = 5'b0;
            endcase
            6'd5 : case (py) // 'E'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b10000;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10000;
                3'd5: rowbits = 5'b10000;
                3'd6: rowbits = 5'b11111;
                default: rowbits = 5'b0;
            endcase
            6'd6 : case (py) // 'F'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b10000;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10000;
                3'd5: rowbits = 5'b10000;
                3'd6: rowbits = 5'b10000;
                default: rowbits = 5'b0;
            endcase
            6'd7 : case (py) // 'G'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b10111;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd8 : case (py) // 'H'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b11111;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd9 : case (py) // 'I'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00100;
                3'd2: rowbits = 5'b00100;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b00100;
                3'd5: rowbits = 5'b00100;
                3'd6: rowbits = 5'b11111;
                default: rowbits = 5'b0;
            endcase
            6'd10: case (py) // 'J'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00010;
                3'd2: rowbits = 5'b00010;
                3'd3: rowbits = 5'b00010;
                3'd4: rowbits = 5'b10010;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b01100;
                default: rowbits = 5'b0;
            endcase
            6'd11: case (py) // 'K'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10010;
                3'd2: rowbits = 5'b10100;
                3'd3: rowbits = 5'b11000;
                3'd4: rowbits = 5'b10100;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd12: case (py) // 'L'
                3'd0: rowbits = 5'b10000;
                3'd1: rowbits = 5'b10000;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b10000;
                3'd4: rowbits = 5'b10000;
                3'd5: rowbits = 5'b10000;
                3'd6: rowbits = 5'b11111;
                default: rowbits = 5'b0;
            endcase
            6'd13: case (py) // 'M'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b11011;
                3'd2: rowbits = 5'b10101;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd14: case (py) // 'N'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b11001;
                3'd2: rowbits = 5'b10101;
                3'd3: rowbits = 5'b10011;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd15: case (py) // 'O'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd16: case (py) // 'P'
                3'd0: rowbits = 5'b11110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10000;
                3'd5: rowbits = 5'b10000;
                3'd6: rowbits = 5'b10000;
                default: rowbits = 5'b0;
            endcase
            6'd17: case (py) // 'Q'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10101;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b01101;
                default: rowbits = 5'b0;
            endcase
            6'd18: case (py) // 'R'
                3'd0: rowbits = 5'b11110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10100;
                3'd5: rowbits = 5'b10010;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd19: case (py) // 'S'
                3'd0: rowbits = 5'b01111;
                3'd1: rowbits = 5'b10000;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b01110;
                3'd4: rowbits = 5'b00001;
                3'd5: rowbits = 5'b00001;
                3'd6: rowbits = 5'b11110;
                default: rowbits = 5'b0;
            endcase
            6'd20: case (py) // 'T'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00100;
                3'd2: rowbits = 5'b00100;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b00100;
                3'd5: rowbits = 5'b00100;
                3'd6: rowbits = 5'b00100;
                default: rowbits = 5'b0;
            endcase
            6'd21: case (py) // 'U'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd22: case (py) // 'V'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b01010;
                3'd6: rowbits = 5'b00100;
                default: rowbits = 5'b0;
            endcase
            6'd23: case (py) // 'W'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b10001;
                3'd4: rowbits = 5'b10101;
                3'd5: rowbits = 5'b11011;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd24: case (py) // 'X'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b01010;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b01010;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b10001;
                default: rowbits = 5'b0;
            endcase
            6'd25: case (py) // 'Y'
                3'd0: rowbits = 5'b10001;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b01010;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b00100;
                3'd5: rowbits = 5'b00100;
                3'd6: rowbits = 5'b00100;
                default: rowbits = 5'b0;
            endcase
            6'd26: case (py) // 'Z'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00001;
                3'd2: rowbits = 5'b00010;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b01000;
                3'd5: rowbits = 5'b10000;
                3'd6: rowbits = 5'b11111;
                default: rowbits = 5'b0;
            endcase
            6'd27: case (py) // '0'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10011;
                3'd3: rowbits = 5'b10101;
                3'd4: rowbits = 5'b11001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd28: case (py) // '1'
                3'd0: rowbits = 5'b00100;
                3'd1: rowbits = 5'b01100;
                3'd2: rowbits = 5'b00100;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b00100;
                3'd5: rowbits = 5'b00100;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd29: case (py) // '2'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b00001;
                3'd3: rowbits = 5'b00010;
                3'd4: rowbits = 5'b00100;
                3'd5: rowbits = 5'b01000;
                3'd6: rowbits = 5'b11111;
                default: rowbits = 5'b0;
            endcase
            6'd30: case (py) // '3'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00010;
                3'd2: rowbits = 5'b00100;
                3'd3: rowbits = 5'b00010;
                3'd4: rowbits = 5'b00001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd31: case (py) // '4'
                3'd0: rowbits = 5'b00010;
                3'd1: rowbits = 5'b00110;
                3'd2: rowbits = 5'b01010;
                3'd3: rowbits = 5'b10010;
                3'd4: rowbits = 5'b11111;
                3'd5: rowbits = 5'b00010;
                3'd6: rowbits = 5'b00010;
                default: rowbits = 5'b0;
            endcase
            6'd32: case (py) // '5'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b10000;
                3'd2: rowbits = 5'b11110;
                3'd3: rowbits = 5'b00001;
                3'd4: rowbits = 5'b00001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd33: case (py) // '6'
                3'd0: rowbits = 5'b00110;
                3'd1: rowbits = 5'b01000;
                3'd2: rowbits = 5'b10000;
                3'd3: rowbits = 5'b11110;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd34: case (py) // '7'
                3'd0: rowbits = 5'b11111;
                3'd1: rowbits = 5'b00001;
                3'd2: rowbits = 5'b00010;
                3'd3: rowbits = 5'b00100;
                3'd4: rowbits = 5'b01000;
                3'd5: rowbits = 5'b01000;
                3'd6: rowbits = 5'b01000;
                default: rowbits = 5'b0;
            endcase
            6'd35: case (py) // '8'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b01110;
                3'd4: rowbits = 5'b10001;
                3'd5: rowbits = 5'b10001;
                3'd6: rowbits = 5'b01110;
                default: rowbits = 5'b0;
            endcase
            6'd36: case (py) // '9'
                3'd0: rowbits = 5'b01110;
                3'd1: rowbits = 5'b10001;
                3'd2: rowbits = 5'b10001;
                3'd3: rowbits = 5'b01111;
                3'd4: rowbits = 5'b00001;
                3'd5: rowbits = 5'b00010;
                3'd6: rowbits = 5'b01100;
                default: rowbits = 5'b0;
            endcase
        endcase
        pix = rowbits[4 - px];
    end
endmodule

// ----------------------------------------------------------------------------
// Hill silhouette: 64 columns, 5-bit height (0..31), repeats horizontally
// ----------------------------------------------------------------------------
module gfx_hill (
    input  wire [5:0] col,
    output reg  [4:0] height
);
    always @* begin
        case (col)
            6'd0 : height = 5'd14;
            6'd1 : height = 5'd17;
            6'd2 : height = 5'd18;
            6'd3 : height = 5'd17;
            6'd4 : height = 5'd15;
            6'd5 : height = 5'd13;
            6'd6 : height = 5'd12;
            6'd7 : height = 5'd12;
            6'd8 : height = 5'd14;
            6'd9 : height = 5'd16;
            6'd10: height = 5'd16;
            6'd11: height = 5'd14;
            6'd12: height = 5'd11;
            6'd13: height = 5'd6 ;
            6'd14: height = 5'd1 ;
            6'd15: height = 5'd0 ;
            6'd16: height = 5'd0 ;
            6'd17: height = 5'd0 ;
            6'd18: height = 5'd0 ;
            6'd19: height = 5'd5 ;
            6'd20: height = 5'd9 ;
            6'd21: height = 5'd12;
            6'd22: height = 5'd13;
            6'd23: height = 5'd13;
            6'd24: height = 5'd12;
            6'd25: height = 5'd11;
            6'd26: height = 5'd11;
            6'd27: height = 5'd13;
            6'd28: height = 5'd16;
            6'd29: height = 5'd19;
            6'd30: height = 5'd20;
            6'd31: height = 5'd19;
            6'd32: height = 5'd16;
            6'd33: height = 5'd10;
            6'd34: height = 5'd5 ;
            6'd35: height = 5'd0 ;
            6'd36: height = 5'd0 ;
            6'd37: height = 5'd0 ;
            6'd38: height = 5'd0 ;
            6'd39: height = 5'd3 ;
            6'd40: height = 5'd6 ;
            6'd41: height = 5'd8 ;
            6'd42: height = 5'd9 ;
            6'd43: height = 5'd8 ;
            6'd44: height = 5'd7 ;
            6'd45: height = 5'd7 ;
            6'd46: height = 5'd8 ;
            6'd47: height = 5'd11;
            6'd48: height = 5'd15;
            6'd49: height = 5'd19;
            6'd50: height = 5'd22;
            6'd51: height = 5'd22;
            6'd52: height = 5'd20;
            6'd53: height = 5'd15;
            6'd54: height = 5'd9 ;
            6'd55: height = 5'd4 ;
            6'd56: height = 5'd1 ;
            6'd57: height = 5'd0 ;
            6'd58: height = 5'd1 ;
            6'd59: height = 5'd3 ;
            6'd60: height = 5'd5 ;
            6'd61: height = 5'd6 ;
            6'd62: height = 5'd6 ;
            6'd63: height = 5'd4 ;
            default: height = 5'd0;
        endcase
    end
endmodule

// ----------------------------------------------------------------------------
// Text strings for the UI, addressed as (screen, line, character position).
//   screen 0 = title screen,  screen 1 = game over screen
//   line   0 = big top line,   line   1 = prompt line
// ----------------------------------------------------------------------------
module gfx_text (
    input  wire       screen,
    input  wire       line,
    input  wire [3:0] idx,
    output reg  [5:0] glyph
);
    reg [1:0] sel;
    always @* begin
        sel = {screen, line};
        case (sel)
            2'b00: case (idx) // "FLAPPY BIRD "
                4'd0 : glyph = 6'd6 ; // 'F'
                4'd1 : glyph = 6'd12; // 'L'
                4'd2 : glyph = 6'd1 ; // 'A'
                4'd3 : glyph = 6'd16; // 'P'
                4'd4 : glyph = 6'd16; // 'P'
                4'd5 : glyph = 6'd25; // 'Y'
                4'd6 : glyph = 6'd0 ; // ' '
                4'd7 : glyph = 6'd2 ; // 'B'
                4'd8 : glyph = 6'd9 ; // 'I'
                4'd9 : glyph = 6'd18; // 'R'
                4'd10: glyph = 6'd4 ; // 'D'
                4'd11: glyph = 6'd0 ; // ' '
                default: glyph = 6'd0;
            endcase
            2'b01: case (idx) // "PRESS SW5   "
                4'd0 : glyph = 6'd16; // 'P'
                4'd1 : glyph = 6'd18; // 'R'
                4'd2 : glyph = 6'd5 ; // 'E'
                4'd3 : glyph = 6'd19; // 'S'
                4'd4 : glyph = 6'd19; // 'S'
                4'd5 : glyph = 6'd0 ; // ' '
                4'd6 : glyph = 6'd19; // 'S'
                4'd7 : glyph = 6'd23; // 'W'
                4'd8 : glyph = 6'd32; // '5'
                4'd9 : glyph = 6'd0 ; // ' '
                4'd10: glyph = 6'd0 ; // ' '
                4'd11: glyph = 6'd0 ; // ' '
                default: glyph = 6'd0;
            endcase
            2'b10: case (idx) // "GAME OVER   "
                4'd0 : glyph = 6'd7 ; // 'G'
                4'd1 : glyph = 6'd1 ; // 'A'
                4'd2 : glyph = 6'd13; // 'M'
                4'd3 : glyph = 6'd5 ; // 'E'
                4'd4 : glyph = 6'd0 ; // ' '
                4'd5 : glyph = 6'd15; // 'O'
                4'd6 : glyph = 6'd22; // 'V'
                4'd7 : glyph = 6'd5 ; // 'E'
                4'd8 : glyph = 6'd18; // 'R'
                4'd9 : glyph = 6'd0 ; // ' '
                4'd10: glyph = 6'd0 ; // ' '
                4'd11: glyph = 6'd0 ; // ' '
                default: glyph = 6'd0;
            endcase
            2'b11: case (idx) // "PRESS SW5   "
                4'd0 : glyph = 6'd16; // 'P'
                4'd1 : glyph = 6'd18; // 'R'
                4'd2 : glyph = 6'd5 ; // 'E'
                4'd3 : glyph = 6'd19; // 'S'
                4'd4 : glyph = 6'd19; // 'S'
                4'd5 : glyph = 6'd0 ; // ' '
                4'd6 : glyph = 6'd19; // 'S'
                4'd7 : glyph = 6'd23; // 'W'
                4'd8 : glyph = 6'd32; // '5'
                4'd9 : glyph = 6'd0 ; // ' '
                4'd10: glyph = 6'd0 ; // ' '
                4'd11: glyph = 6'd0 ; // ' '
                default: glyph = 6'd0;
            endcase
        endcase
    end
endmodule

// Glyph indices (6-bit): ' '=0 A=1 B=2 C=3 D=4 E=5 F=6 G=7 H=8 I=9 J=10 K=11 L=12 M=13 N=14 O=15 P=16 Q=17 R=18 S=19 T=20 U=21 V=22 W=23 X=24 Y=25 Z=26 0=27 1=28 2=29 3=30 4=31 5=32 6=33 7=34 8=35 9=36
// (digits 0-9 are glyph 27..36, i.e. 6'd27 + digit)

